In [ ]:
import numpy as np

In [ ]:
a=np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

# **Reshape**

In [ ]:
a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

# **New axis**

In [ ]:
a.shape

(6,)

In [ ]:
d=a[np.newaxis, :]
print(d)
print(d.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [ ]:
d=a[ :, np.newaxis]
print(d)
print(d.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


# **Concatenation**

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
c = np.concatenate((a, b), axis=None)
print(c)

[1 2 3 4 5 6]


In [ ]:
d = np.concatenate((a, b), axis=0)
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
e = np.concatenate((a, b.T), axis=1)
print(e)

[[1 2 5]
 [3 4 6]]


# **Horizontal stack and vertical stack**

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.hstack((a,b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# **Broadcasting**

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1, 0, 1])
z = x + y  # Add v to each row of x using broadcasting
print(z) 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# **Axis**

In [ ]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])

print(a.sum())          # default=None-> 210
print(a.sum(axis=None)) # overall sum -> 210

print(a.sum(axis=0)) # along the rows -> 1 sum entry for each column
# -> [24 26 28 30 32 34 36]

print(a.sum(axis=1)) # along the columns -> 1 sum entry for each row
# -> [ 70 140]


210
210
[24 26 28 30 32 34 36]
[ 70 140]


# **copying**

In [ ]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])

b = a.copy()
a[0][0]=99999
print(a, b, sep="\n\n")

[[99999     8     9    10    11    12    13]
 [   17    18    19    20    21    22    23]]

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]


# **Generating arrays**


In [ ]:

# zeros
a = np.zeros((2,3)) # size as tuple
# [[0. 0. 0.]
#  [0. 0. 0.]]

# ones
b = np.ones((2,3))
# [[1. 1. 1.]
#  [1. 1. 1.]]

# specific value
c = np.full((3,3),5.0)
# [[5. 5. 5.]
#  [5. 5. 5.]
#  [5. 5. 5.]]

# identity
d = np.eye(3) #3x3
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# arange
e = np.arange(10)
# [0 1 2 3 4 5 6 7 8 9]

# linspace
f = np.linspace(0, 10, 5)
# [ 0.  2.5  5.  7.5  10. ]

# **Random numbers**

In [ ]:
a = np.random.random((3,2)) # uniform 0-1 distribution
# [[0.06121857 0.10180167]
#  [0.83321726 0.54906613]
#  [0.94170273 0.19447411]]

b = np.random.randn(3,2) # normal/Gaussian distribution, mean 0 and unit variance
# no tuple as shape here! each dimension one argument
# [[ 0.56759123 -0.65068333]
#  [ 0.83445762 -0.36436185]
#  [ 1.27150812 -0.32906051]]

c = np.random.randn(10000)
print(c.mean(), c.var(), c.std())
# -0.0014 0.9933 0.9966

d = np.random.randn(10, 3)
print(d.mean()) # mean of whole array: -0.1076827228882305

# random integer, low,high,size; high is exclusive
e = np.random.randint(3,10,size=(3,3)) # if we only pass one parameter, then from 0-x
print(e)
# [[6 8 4]
#  [3 6 3]
#  [4 7 8]]

# with integer is between 0 up to integer exclusive
f = np.random.choice(7, size=10)
# [2 0 4 5 1 3 4 0 0 6]

# with an array it draws random values from this array
g = np.random.choice([1,2,3,4], size=8)
# [4 2 1 3 4 1 4 1]

-0.007898355990622715 0.995277705843364 0.9976360588127134
-0.1885411115601423
[[4 4 5]
 [3 9 3]
 [9 5 7]]


# **Solving linear equation with two variables**

In [ ]:
#     x1 + x2   = 2200
# 1.5 x1 + 4 x2 = 5050
# -> 2 equations and 2 unknowns
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200,5050])

# Ax = b <=> x = A-1 b

# But: inverse is slow and less accurate
x = np.linalg.inv(A).dot(b) # not recommended
print(x) # [1500.  700.]

# instead use:
x = np.linalg.solve(A,b) # good
print(x) # [1500.  700.]

[1500.  700.]
[1500.  700.]
